version: '3.4'

services:
  db:
    container_name: MSSQL
    image: "mcr.microsoft.com/mssql/server:2019-latest"

  webstore:
    image: ${DOCKER_REGISTRY-}webstore
    build:
      context: .
      dockerfile: WebStore/Dockerfile
